name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: mkdir staging && cp target/*.jar staging
    - uses: actions/upload-artifact@v1
      with:
            name: Package
            path: staging
    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag trapthyshetty/demorepo:1
    - name: Publish Docker image
      run: docker push trapthyshetty/demorepo:1
    - name: Snyk Container Test
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ Secrets.SNYK_TOKEN }}
      with:
        image: trapthyshetty/demorepo:1
        args: --file=Dockerfile
#     - name: Build and push Docker images
#       uses: docker/build-push-action@v3.2.0
#       with:
#           tags: trapthyshetty/demo123
   
